# Default values for currency.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 100.69.158.196/bitcoin
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

nodeport: 3010

configuration:
  pod_directory: /usr/share/nginx/html/conf
  files:
    vertcoin.conf: |
      abc=xyz
      #a=1
      b=2
    second.conf: |
      fsdf'sd
      Fixtures.identify(:sdf'
      sdf
      'sdf
      ')

persistentvolumeclaims:
  mountPath: /usr/share/nginx/html/faldax-nodejs/.tmp/uploads

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /

  hosts:
    - pre-prod-bitcoin.faldax.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
   cpu: 300m
   memory: 412Mi
  requests:
   cpu: 200m
   memory: 256Mi

tolerations:
- key: env
  operator: Equal
  value: jenkins
  effect: NoSchedule
- key: kops.k8s.io/instancegroup
  operator: Equal
  value: nodes
  effect: NoSchedule
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: env
          operator: In
          values:
          - jenkins
      - matchExpressions:
        - key: kops.k8s.io/instancegroup
          operator: In
          values:
          - nodes

affinity: {}

controller:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 90

health:
  enable: false
  livenessProbe:
    path: /health-check
    port: 1337
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    path: /health-check
    port: 1337
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 5